language: python
python:
  - "2.6"
  - "2.7"

addons:
  apt:
    packages:
      - libenchant-dev

install:
  - "pip install -r requirements.txt"
  - "pip install pep8"

before_script: "pep8 --max-line-length=100 ."

# Perform self test
script: "python ./sourcespell/sourcespell.py -I '*conf.py' '*_build*' '*_templates*' '*Makefile' '*.egg-info/*' 'docs/*' 'LICENSE' '*.txt' '*.bat'"